### ISSUE TITLE
login button takes user to /login, not logins erb

### ISSUE THREAD

**Issue by KaraAJC** [chi-squirrels-2015/flippit-flashcards#14]
the login button on the index file takes the user to this URL: http://localhost:9393/login?
and sinatra is asking for the following route: 

```
Try this:
get '/login' do
  "Hello World"
end
```

but in  our index controller we are asking for logins: 

``` ruby
get '/logins' do
    erb :"/logins"
end
```

**Comment by PacoGuy** [comment]
Updated, submitting pull request for merge.

**Comment by PacoGuy** [comment]
Tested and displaying proper page when login button is pressed
