### ISSUE TITLE
sign up button takes users to new_users, not users/new

### ISSUE THREAD

**Issue by KaraAJC** [chi-squirrels-2015/flippit-flashcards#15]
clicking the sign up button on the index takes the user to the following URL: http://localhost:9393/new_users?

but in our controller for users we have:

``` ruby
# users.rb
post '/users/new' do
    user = User.new
```

ALSO there is no get route for users/new

**Comment by PacoGuy** [comment]
Updated, submitting pull request for merge.

**Comment by PacoGuy** [comment]
Merge successful, may still need /users/new get route
